//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_PKLMilitia {
        displayName = "[CKN] People's Regional Militia";
        side = 0;
        flag = "\A3\Ui_f\data\Map\Markers\Flags\viper_ca.paa";
        icon = "\A3\Ui_f\data\Map\Markers\Flags\viper_ca.paa";
        priority = 3;
    };
};

class CfgGroups {
    class EAST {

        class O_PKLMilitia {
            name = "[CKN] People's Regional Militia";

            class Infantry {
                name = "Infantry";

                class o_pklmilitia_infantry_paramilitary_fire_team {
                    name = "Paramilitary Fire Team";
                    side = 0;
                    faction = "O_PKLMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLMilitia_Enforcer_Rifle_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Oppressor_Machine_Gun_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLMilitia_Soldier_Rifle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Militiaman_Medikit_01";
                    };
                };

                class o_pklmilitia_infantry_paramilitary_shock_team {
                    name = "Paramilitary Shock Team";
                    side = 0;
                    faction = "O_PKLMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLMilitia_Raider_UGL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Specialist_Launcher_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLMilitia_Deserter_Rifle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Saboteur_Explosives_01";
                    };
                };

                class o_pklmilitia_infantry_paramilitary_combat_group {
                    name = "Paramilitary Combat Group";
                    side = 0;
                    faction = "O_PKLMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLMilitia_Enforcer_Rifle_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Oppressor_Machine_Gun_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLMilitia_Raider_UGL_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLMilitia_Soldier_Rifle_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLMilitia_Deserter_Rifle_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Specialist_Launcher_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Saboteur_Explosives_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Militiaman_Medikit_01";
                    };
                };

                class o_pklmilitia_infantry_bandit_fire_team {
                    name = "Bandit Fire Team";
                    side = 0;
                    faction = "O_PKLMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLMilitia_Watcher_Rifle_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Guard_Machine_Gun_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLMilitia_Scout_Rifle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Snatcher_Medikit_01";
                    };
                };

                class o_pklmilitia_infantry_bandit_shock_team {
                    name = "Bandit Shock Team";
                    side = 0;
                    faction = "O_PKLMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLMilitia_Smuggler_UGL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Hireling_Launcher_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLMilitia_Dealer_Rifle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Thug_Mines_01";
                    };
                };

                class o_pklmilitia_infantry_bandit_combat_group {
                    name = "Bandit Combat Group";
                    side = 0;
                    faction = "O_PKLMilitia";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLMilitia_Watcher_Rifle_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Guard_Machine_Gun_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLMilitia_Dealer_Rifle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLMilitia_Scout_Rifle_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLMilitia_Smuggler_UGL_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Hireling_Launcher_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Thug_Mines_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLMilitia_Snatcher_Medikit_01";
                    };
                };

            };

            class SpecOps {
                name = "Special Forces";

            };

            class Motorized {
                name = "Motorized Infantry";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support Infantry";

            };

            class Mechanized {
                name = "Mechanized Infantry";

            };

            class Armored {
                name = "Armor";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_C_Helipilot_F;
    class I_C_Helipilot_F_OCimport_01 : I_C_Helipilot_F { scope = 0; class EventHandlers; };
    class I_C_Helipilot_F_OCimport_02 : I_C_Helipilot_F_OCimport_01 { class EventHandlers; };

    class I_C_Pilot_F;
    class I_C_Pilot_F_OCimport_01 : I_C_Pilot_F { scope = 0; class EventHandlers; };
    class I_C_Pilot_F_OCimport_02 : I_C_Pilot_F_OCimport_01 { class EventHandlers; };

    class I_C_Soldier_Para_8_F;
    class I_C_Soldier_Para_8_F_OCimport_01 : I_C_Soldier_Para_8_F { scope = 0; class EventHandlers; };
    class I_C_Soldier_Para_8_F_OCimport_02 : I_C_Soldier_Para_8_F_OCimport_01 { class EventHandlers; };

    class I_C_Soldier_Para_7_F;
    class I_C_Soldier_Para_7_F_OCimport_01 : I_C_Soldier_Para_7_F { scope = 0; class EventHandlers; };
    class I_C_Soldier_Para_7_F_OCimport_02 : I_C_Soldier_Para_7_F_OCimport_01 { class EventHandlers; };

    class I_C_Soldier_Para_6_F;
    class I_C_Soldier_Para_6_F_OCimport_01 : I_C_Soldier_Para_6_F { scope = 0; class EventHandlers; };
    class I_C_Soldier_Para_6_F_OCimport_02 : I_C_Soldier_Para_6_F_OCimport_01 { class EventHandlers; };

    class I_C_Soldier_Para_5_F;
    class I_C_Soldier_Para_5_F_OCimport_01 : I_C_Soldier_Para_5_F { scope = 0; class EventHandlers; };
    class I_C_Soldier_Para_5_F_OCimport_02 : I_C_Soldier_Para_5_F_OCimport_01 { class EventHandlers; };

    class I_C_Soldier_Para_4_F;
    class I_C_Soldier_Para_4_F_OCimport_01 : I_C_Soldier_Para_4_F { scope = 0; class EventHandlers; };
    class I_C_Soldier_Para_4_F_OCimport_02 : I_C_Soldier_Para_4_F_OCimport_01 { class EventHandlers; };

    class I_C_Soldier_Para_3_F;
    class I_C_Soldier_Para_3_F_OCimport_01 : I_C_Soldier_Para_3_F { scope = 0; class EventHandlers; };
    class I_C_Soldier_Para_3_F_OCimport_02 : I_C_Soldier_Para_3_F_OCimport_01 { class EventHandlers; };

    class I_C_Soldier_Para_2_F;
    class I_C_Soldier_Para_2_F_OCimport_01 : I_C_Soldier_Para_2_F { scope = 0; class EventHandlers; };
    class I_C_Soldier_Para_2_F_OCimport_02 : I_C_Soldier_Para_2_F_OCimport_01 { class EventHandlers; };

    class I_C_Soldier_Para_1_F;
    class I_C_Soldier_Para_1_F_OCimport_01 : I_C_Soldier_Para_1_F { scope = 0; class EventHandlers; };
    class I_C_Soldier_Para_1_F_OCimport_02 : I_C_Soldier_Para_1_F_OCimport_01 { class EventHandlers; };

    class UK3CB_CW_SOV_O_EARLY_BRDM2;
    class UK3CB_CW_SOV_O_EARLY_BRDM2_OCimport_01 : UK3CB_CW_SOV_O_EARLY_BRDM2 { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_BRDM2_OCimport_02 : UK3CB_CW_SOV_O_EARLY_BRDM2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CommanderOptics;
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_BRDM2_UM;
    class UK3CB_CW_SOV_O_EARLY_BRDM2_UM_OCimport_01 : UK3CB_CW_SOV_O_EARLY_BRDM2_UM { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_BRDM2_UM_OCimport_02 : UK3CB_CW_SOV_O_EARLY_BRDM2_UM_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CommanderOptics;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_UAZ_Closed;
    class UK3CB_CW_SOV_O_EARLY_UAZ_Closed_OCimport_01 : UK3CB_CW_SOV_O_EARLY_UAZ_Closed { scope = 0; class EventHandlers; };
    class UK3CB_CW_SOV_O_EARLY_UAZ_Closed_OCimport_02 : UK3CB_CW_SOV_O_EARLY_UAZ_Closed_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_CW_SOV_O_EARLY_UAZ_AGS30;
    class UK3CB_CW_SOV_O_EARLY_UAZ_AGS30_OCimport_01 : UK3CB_CW_SOV_O_EARLY_UAZ_AGS30 { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_UAZ_AGS30_OCimport_02 : UK3CB_CW_SOV_O_EARLY_UAZ_AGS30_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_UAZ_MG;
    class UK3CB_CW_SOV_O_EARLY_UAZ_MG_OCimport_01 : UK3CB_CW_SOV_O_EARLY_UAZ_MG { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_UAZ_MG_OCimport_02 : UK3CB_CW_SOV_O_EARLY_UAZ_MG_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_UAZ_SPG9;
    class UK3CB_CW_SOV_O_EARLY_UAZ_SPG9_OCimport_01 : UK3CB_CW_SOV_O_EARLY_UAZ_SPG9 { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_UAZ_SPG9_OCimport_02 : UK3CB_CW_SOV_O_EARLY_UAZ_SPG9_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_Ural;
    class UK3CB_CW_SOV_O_EARLY_Ural_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Ural { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_Ural_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Ural_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_Ural_Ammo;
    class UK3CB_CW_SOV_O_EARLY_Ural_Ammo_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Ural_Ammo { scope = 0; class EventHandlers; };
    class UK3CB_CW_SOV_O_EARLY_Ural_Ammo_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Ural_Ammo_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_CW_SOV_O_EARLY_Ural_Empty;
    class UK3CB_CW_SOV_O_EARLY_Ural_Empty_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Ural_Empty { scope = 0; class EventHandlers; };
    class UK3CB_CW_SOV_O_EARLY_Ural_Empty_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Ural_Empty_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_CW_SOV_O_EARLY_Ural_Fuel;
    class UK3CB_CW_SOV_O_EARLY_Ural_Fuel_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Ural_Fuel { scope = 0; class EventHandlers; };
    class UK3CB_CW_SOV_O_EARLY_Ural_Fuel_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Ural_Fuel_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_CW_SOV_O_EARLY_Ural_Open;
    class UK3CB_CW_SOV_O_EARLY_Ural_Open_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Ural_Open { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_Ural_Open_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Ural_Open_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_Ural_Recovery;
    class UK3CB_CW_SOV_O_EARLY_Ural_Recovery_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Ural_Recovery { scope = 0; class EventHandlers; };
    class UK3CB_CW_SOV_O_EARLY_Ural_Recovery_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Ural_Recovery_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_CW_SOV_O_EARLY_Ural_Repair;
    class UK3CB_CW_SOV_O_EARLY_Ural_Repair_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Ural_Repair { scope = 0; class EventHandlers; };
    class UK3CB_CW_SOV_O_EARLY_Ural_Repair_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Ural_Repair_OCimport_01 { scope = 0; class EventHandlers; };

    class UK3CB_CW_SOV_O_EARLY_Ural_Zu23;
    class UK3CB_CW_SOV_O_EARLY_Ural_Zu23_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Ural_Zu23 { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_Ural_Zu23_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Ural_Zu23_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_Mi8;
    class UK3CB_CW_SOV_O_EARLY_Mi8_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Mi8 { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_Mi8_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Mi8_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class MainTurret;
            class BackTurret;
        };
    };

    class UK3CB_CW_SOV_O_EARLY_Antonov_AN2;
    class UK3CB_CW_SOV_O_EARLY_Antonov_AN2_OCimport_01 : UK3CB_CW_SOV_O_EARLY_Antonov_AN2 { scope = 0; class EventHandlers; class Turrets; };
    class UK3CB_CW_SOV_O_EARLY_Antonov_AN2_OCimport_02 : UK3CB_CW_SOV_O_EARLY_Antonov_AN2_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret01;
            class CargoTurret02;
        };
    };


    class O_PKLMilitia_Helicopter_Pilot_01 : I_C_Helipilot_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Helicopter Pilot";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_2";

        linkedItems[] = {"rhsgref_chicom","rhs_gssh18","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_chicom","rhs_gssh18","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u"};
        respawnWeapons[] = {"rhs_weap_aks74u"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_TLA_2",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"rhsgref_chicom",{}},{},"rhs_gssh18","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Pilot_01 : I_C_Pilot_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_2";

        linkedItems[] = {"rhsgref_chicom","rhs_gssh18","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_chicom","rhs_gssh18","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u"};
        respawnWeapons[] = {"rhs_weap_aks74u"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_TLA_2",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"rhsgref_chicom",{}},{},"rhs_gssh18","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Saboteur_Explosives_01 : I_C_Soldier_Para_8_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Saboteur (Explosives)";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_1";

        linkedItems[] = {"UK3CB_LSM_B_H_BoonieHat_KHK","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_LSM_B_H_BoonieHat_KHK","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74"};
        respawnWeapons[] = {"rhs_weap_ak74"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "B_Carryall_oli";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_TLA_1",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{},{"B_Carryall_oli",{{"ToolKit",1},{"DemoCharge_Remote_Mag",3,1},{"SatchelCharge_Remote_Mag",1,1}}},"UK3CB_LSM_B_H_BoonieHat_KHK","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Deserter_Rifle_01 : I_C_Soldier_Para_7_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Deserter (Rifle)";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_2";

        linkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74"};
        respawnWeapons[] = {"rhs_weap_ak74"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_TLA_2",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"rhsgref_chicom",{{"rhs_30Rnd_545x39_7N6M_AK",10,30}}},{},"rhsgref_hat_m1941cap","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Raider_UGL_01 : I_C_Soldier_Para_6_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Raider (UGL)";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_1";

        linkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74_gp25"};
        respawnWeapons[] = {"rhs_weap_ak74_gp25"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25","rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25","rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74_gp25","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{"rhs_VOG25",1},""},{},{},{"rhsgref_uniform_TLA_1",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30},{"rhs_VOG25",1,1}}},{"rhsgref_chicom",{{"rhs_VOG25",4,1},{"rhs_30Rnd_545x39_7N6M_AK",5,30}}},{},"rhsgref_hat_m1941cap","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Specialist_Launcher_01 : I_C_Soldier_Para_5_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Specialist (Launcher)";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_2";

        linkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74","rhs_weap_rpg7"};
        respawnWeapons[] = {"rhs_weap_ak74","rhs_weap_rpg7"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_rpg7_PG7VL_mag","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_rpg7_PG7VL_mag","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "rhs_rpg_2";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{"rhs_weap_rpg7","","","",{"rhs_rpg7_PG7VL_mag",1},{},""},{},{"rhsgref_uniform_TLA_2",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"rhsgref_chicom",{{"rhs_30Rnd_545x39_7N6M_AK",10,30}}},{"rhs_rpg_2",{{"rhs_rpg7_PG7VL_mag",2,1},{"rhs_rpg7_OG7V_mag",1,1}}},"rhsgref_hat_m1941cap","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Oppressor_Machine_Gun_01 : I_C_Soldier_Para_4_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Oppressor (Machine Gun)";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_2";

        linkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"UK3CB_RPK_74"};
        respawnWeapons[] = {"UK3CB_RPK_74"};

        magazines[] = {"UK3CB_RPK74_60rnd_545x39","UK3CB_RPK74_60rnd_545x39"};
        respawnMagazines[] = {"UK3CB_RPK74_60rnd_545x39","UK3CB_RPK74_60rnd_545x39"};

        ALiVE_orbatCreator_loadout[] = {{"UK3CB_RPK_74","","","",{"UK3CB_RPK74_60rnd_545x39",60},{},""},{},{},{"rhsgref_uniform_TLA_2",{{"FirstAidKit",1},{"UK3CB_RPK74_60rnd_545x39",1,60}}},{"rhsgref_chicom",{{"UK3CB_RPK74_60rnd_545x39",4,60}}},{},"rhsgref_hat_m1941cap","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Militiaman_Medikit_01 : I_C_Soldier_Para_3_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Militiaman (Medikit)";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_1";

        linkedItems[] = {"rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74"};
        respawnWeapons[] = {"rhs_weap_ak74"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "B_Carryall_oli";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_TLA_1",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{},{"B_Carryall_oli",{{"Medikit",1},{"FirstAidKit",4}}},"rhsgref_hat_m1941cap","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Enforcer_Rifle_01 : I_C_Soldier_Para_2_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Enforcer (Rifle)";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_2";

        linkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74"};
        respawnWeapons[] = {"rhs_weap_ak74"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_TLA_2",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"rhsgref_chicom",{{"rhs_30Rnd_545x39_7N6M_AK",10,30}}},{},"rhsgref_hat_m1941cap","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_Soldier_Rifle_01 : I_C_Soldier_Para_1_F_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Soldier (Rifle)";
        side = 2;
        faction = "O_PKLMilitia";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "rhsgref_uniform_TLA_2";

        linkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"rhsgref_chicom","rhsgref_hat_m1941cap","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74"};
        respawnWeapons[] = {"rhs_weap_ak74"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"rhsgref_uniform_TLA_2",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"rhsgref_chicom",{{"rhs_30Rnd_545x39_7N6M_AK",10,30}}},{},"rhsgref_hat_m1941cap","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLMilitia_BRDM_2_01 : UK3CB_CW_SOV_O_EARLY_BRDM2_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "BRDM-2";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";

        class Turrets : Turrets {
            class CommanderOptics : CommanderOptics { gunnerType = "O_PKLMilitia_Raider_UGL_01"; };
            class MainTurret : MainTurret { gunnerType = "O_PKLMilitia_Soldier_Rifle_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\brdm2_ru_01_co.paa'];_unit setObjectTextureGlobal [1,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\brdm2_02_co.paa'];_unit setObjectTextureGlobal [2,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\zbik_04_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "OLI";

    };

    class O_PKLMilitia_BRDM_2UM_Unarmed_01 : UK3CB_CW_SOV_O_EARLY_BRDM2_UM_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "BRDM-2UM (Unarmed)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";

        class Turrets : Turrets {
            class CommanderOptics : CommanderOptics { gunnerType = "O_PKLMilitia_Raider_UGL_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\brdm2_ru_01_co.paa'];_unit setObjectTextureGlobal [1,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\brdm2_02_co.paa'];_unit setObjectTextureGlobal [2,'\rhsgref\addons\rhsgref_a2port_armor\brdm2\data\zbik_04_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "OLI";

    };

    class O_PKLMilitia_UAZ_3151_Covered_01 : UK3CB_CW_SOV_O_EARLY_UAZ_Closed_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151 (Covered)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_uaz\data\uaz_main_green_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Dark_Green";

    };

    class O_PKLMilitia_UAZ_3151_AGS_30_01 : UK3CB_CW_SOV_O_EARLY_UAZ_AGS30_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151 (AGS-30)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLMilitia_Soldier_Rifle_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_PKLMilitia_Raider_UGL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_uaz\data\uaz_main_green_co.paa'];_unit setObjectTextureGlobal [1,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_uaz\data\uaz_mount_black_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Dark_Green";

    };

    class O_PKLMilitia_UAZ_3151_DShKM_01 : UK3CB_CW_SOV_O_EARLY_UAZ_MG_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151 (DShKM)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLMilitia_Soldier_Rifle_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_PKLMilitia_Raider_UGL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_uaz\data\uaz_main_green_co.paa'];_unit setObjectTextureGlobal [1,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_uaz\data\uaz_mount_black_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Dark_Green";

    };

    class O_PKLMilitia_UAZ_3151_SPG_01 : UK3CB_CW_SOV_O_EARLY_UAZ_SPG9_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151 (SPG-9)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLMilitia_Soldier_Rifle_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_PKLMilitia_Raider_UGL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_uaz\data\uaz_main_green_co.paa'];_unit setObjectTextureGlobal [1,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_uaz\data\uaz_mount_black_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Dark_Green";

    };

    class O_PKLMilitia_Ural_4320_Closed_01 : UK3CB_CW_SOV_O_EARLY_Ural_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural 4320 (Closed)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_PKLMilitia_Soldier_Rifle_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "O_PKLMilitia_Raider_UGL_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_kabina_oli_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\RHS_A2port_car\Ural\Data\ural_plachta_co.paa'];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [5,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [6,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [7,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [8,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [9,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [10,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [11,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_PKLMilitia_Ural_4320_Ammo_01 : UK3CB_CW_SOV_O_EARLY_Ural_Ammo_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320 (Ammo)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_kabina_oli_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\RHS_A2port_car\Ural\Data\ural_plachta_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_PKLMilitia_Ural_4320_Empty_01 : UK3CB_CW_SOV_O_EARLY_Ural_Empty_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320 (Empty)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_kabina_oli_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\RHS_A2port_car\Ural\Data\ural_plachta_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_PKLMilitia_Ural_4320_Fuel_01 : UK3CB_CW_SOV_O_EARLY_Ural_Fuel_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320 (Fuel)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_kabina_oli_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\RHS_A2port_car\Ural\Data\ural_open_co.paa'];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [5,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [6,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [7,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [8,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [9,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [10,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [11,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [12,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_fuel_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_PKLMilitia_Ural_4320_Open_01 : UK3CB_CW_SOV_O_EARLY_Ural_Open_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320 (Open)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_kabina_oli_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\RHS_A2port_car\Ural\Data\ural_open_co.paa'];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [5,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [6,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [7,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [8,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [9,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [10,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [11,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_PKLMilitia_Ural_4320_Recovery_01 : UK3CB_CW_SOV_O_EARLY_Ural_Recovery_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320 (Recovery)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_kabina_oli_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\RHS_A2port_car\Ural\Data\ural_plachta_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_PKLMilitia_Ural_4320_Repair_01 : UK3CB_CW_SOV_O_EARLY_Ural_Repair_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320 (Repair)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_kabina_oli_co.paa'];_unit setObjectTextureGlobal [1,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_repair_oli_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_PKLMilitia_Ural_4320_ZU_23_01 : UK3CB_CW_SOV_O_EARLY_Ural_Zu23_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Ural-4320 (ZU-23)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Soldier_Rifle_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLMilitia_Soldier_Rifle_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = "O_PKLMilitia_Soldier_Rifle_01"; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = "UK3CB_CW_SOV_O_EARLY_RIF_1"; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = "UK3CB_CW_SOV_O_EARLY_RIF_1"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\UK3CB_Factions\addons\UK3CB_Factions_Vehicles\wheeled\UK3CB_Factions_Vehicles_ural\data\ural_kabina_oli_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\RHS_A2port_car\Ural\Data\ural_open_co.paa'];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [5,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [6,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [7,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [8,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [9,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [10,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];_unit setObjectTextureGlobal [11,'\rhsafrf\addons\RHS_Decals\Data\Labels\Misc\no_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Olive";

    };

    class O_PKLMilitia_Mil_Mi8_Transport_01 : UK3CB_CW_SOV_O_EARLY_Mi8_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mil Mi8 (Transport)";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Helicopter_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "O_PKLMilitia_Helicopter_Pilot_01"; };
            class MainTurret : MainTurret { gunnerType = ""; };
            class BackTurret : BackTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_MI8\data\khk_mi8_body_co.paa'];_unit setObjectTextureGlobal [1,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_MI8\data\khk_mi8_det_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "KHK";

    };

    class O_PKLMilitia_Antonov_An_2_01 : UK3CB_CW_SOV_O_EARLY_Antonov_AN2_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Antonov An-2";
        side = 0;
        faction = "O_PKLMilitia";
        crew = "O_PKLMilitia_Pilot_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLMilitia_Pilot_01"; };
            class CargoTurret01 : CargoTurret01 { gunnerType = ""; };
            class CargoTurret02 : CargoTurret02 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_AN2\data\an2_1_olive_co.paa'];_unit setObjectTextureGlobal [1,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_AN2\data\an2_2_olive_co.paa'];_unit setObjectTextureGlobal [2,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_AN2\data\an2_wings_olive_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "OLIVE";

    };

};