//////////////////////////////////////////////////////////////////////////////////
// Config Automatically Generated by ALiVE ORBAT Creator
// Generated with Arma 3 version 216.151618 on Stable branch
// Generated with ALiVE version 2.1.2.2309211
//////////////////////////////////////////////////////////////////////////////////

class CfgFactionClasses {
    class O_PKLGang {
        displayName = "[CKN] Snakehead Syndicate";
        side = 0;
        flag = "\a3\Data_F_Exp\Flags\flag_SYND_CO.paa";
        icon = "\a3\Data_F_Exp\Flags\flag_SYND_CO.paa";
        priority = 3;
    };
};

class CfgGroups {
    class EAST {

        class O_PKLGang {
            name = "[CKN] Snakehead Syndicate";

            class Infantry {
                name = "Infantry";

                class o_pklgang_infantry_bandit_shock_team {
                    name = "Bandit Shock Team";
                    side = 0;
                    faction = "O_PKLGang";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLGang_Smuggler_UGL_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLGang_Hireling_Launcher_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLGang_Dealer_Rifle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLGang_Thug_Mines_01";
                    };
                };

                class o_pklgang_infantry_bandit_fire_team {
                    name = "Bandit Fire Team";
                    side = 0;
                    faction = "O_PKLGang";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLGang_Watcher_Rifle_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLGang_Guard_Machine_Gun_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLGang_Scout_Rifle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLGang_Snatcher_Medikit_01";
                    };
                };

                class o_pklgang_infantry_bandit_combat_group {
                    name = "Bandit Combat Group";
                    side = 0;
                    faction = "O_PKLGang";
                    icon = "\A3\ui_f\data\map\markers\nato\n_inf.paa";
                    rarityGroup = 0.5;

                    class Unit0 {
                        position[] = {0,0,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLGang_Watcher_Rifle_01";
                    };
                    class Unit1 {
                        position[] = {5,-5,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLGang_Guard_Machine_Gun_01";
                    };
                    class Unit2 {
                        position[] = {-5,-5,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLGang_Dealer_Rifle_01";
                    };
                    class Unit3 {
                        position[] = {10,-10,0};
                        rank = "CORPORAL";
                        side = 2;
                        vehicle = "O_PKLGang_Scout_Rifle_01";
                    };
                    class Unit4 {
                        position[] = {-10,-10,0};
                        rank = "SERGEANT";
                        side = 2;
                        vehicle = "O_PKLGang_Smuggler_UGL_01";
                    };
                    class Unit5 {
                        position[] = {15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLGang_Hireling_Launcher_01";
                    };
                    class Unit6 {
                        position[] = {-15,-15,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLGang_Thug_Mines_01";
                    };
                    class Unit7 {
                        position[] = {20,-20,0};
                        rank = "PRIVATE";
                        side = 2;
                        vehicle = "O_PKLGang_Snatcher_Medikit_01";
                    };
                };

            };

            class SpecOps {
                name = "SpecOps";

            };

            class Motorized {
                name = "Motorized";

            };

            class Motorized_MTP {
                name = "Motorized Infantry (MTP)";

            };

            class Support {
                name = "Support";

            };

            class Mechanized {
                name = "Mechanized";

            };

            class Armored {
                name = "Armored";

            };

            class Artillery {
                name = "Artillery";

            };

            class Naval {
                name = "Naval";

            };

            class Air {
                name = "Air";

            };


        };

    };
};


class CBA_Extended_EventHandlers_base;

class CfgVehicles {

    class I_PKLGang_T41_Mescalero_01;
    class I_PKLGang_T41_Mescalero_01_OCimport_01 : I_PKLGang_T41_Mescalero_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_T41_Mescalero_01_OCimport_02 : I_PKLGang_T41_Mescalero_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_PKLGang_Rifleman_Unarmed_01;
    class I_PKLGang_Rifleman_Unarmed_01_OCimport_01 : I_PKLGang_Rifleman_Unarmed_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Rifleman_Unarmed_01_OCimport_02 : I_PKLGang_Rifleman_Unarmed_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Helicopter_Pilot_01;
    class I_PKLGang_Helicopter_Pilot_01_OCimport_01 : I_PKLGang_Helicopter_Pilot_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Helicopter_Pilot_01_OCimport_02 : I_PKLGang_Helicopter_Pilot_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Pilot_01;
    class I_PKLGang_Pilot_01_OCimport_01 : I_PKLGang_Pilot_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Pilot_01_OCimport_02 : I_PKLGang_Pilot_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Snatcher_Medikit_01;
    class I_PKLGang_Snatcher_Medikit_01_OCimport_01 : I_PKLGang_Snatcher_Medikit_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Snatcher_Medikit_01_OCimport_02 : I_PKLGang_Snatcher_Medikit_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Thug_Mines_01;
    class I_PKLGang_Thug_Mines_01_OCimport_01 : I_PKLGang_Thug_Mines_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Thug_Mines_01_OCimport_02 : I_PKLGang_Thug_Mines_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Dealer_Rifle_01;
    class I_PKLGang_Dealer_Rifle_01_OCimport_01 : I_PKLGang_Dealer_Rifle_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Dealer_Rifle_01_OCimport_02 : I_PKLGang_Dealer_Rifle_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Smuggler_UGL_01;
    class I_PKLGang_Smuggler_UGL_01_OCimport_01 : I_PKLGang_Smuggler_UGL_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Smuggler_UGL_01_OCimport_02 : I_PKLGang_Smuggler_UGL_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Scout_Rifle_01;
    class I_PKLGang_Scout_Rifle_01_OCimport_01 : I_PKLGang_Scout_Rifle_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Scout_Rifle_01_OCimport_02 : I_PKLGang_Scout_Rifle_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Watcher_Rifle_01;
    class I_PKLGang_Watcher_Rifle_01_OCimport_01 : I_PKLGang_Watcher_Rifle_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Watcher_Rifle_01_OCimport_02 : I_PKLGang_Watcher_Rifle_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Guard_Machine_Gun_01;
    class I_PKLGang_Guard_Machine_Gun_01_OCimport_01 : I_PKLGang_Guard_Machine_Gun_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Guard_Machine_Gun_01_OCimport_02 : I_PKLGang_Guard_Machine_Gun_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_Hireling_Launcher_01;
    class I_PKLGang_Hireling_Launcher_01_OCimport_01 : I_PKLGang_Hireling_Launcher_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_Hireling_Launcher_01_OCimport_02 : I_PKLGang_Hireling_Launcher_01_OCimport_01 { class EventHandlers; };

    class I_PKLGang_UAZ_3151_01;
    class I_PKLGang_UAZ_3151_01_OCimport_01 : I_PKLGang_UAZ_3151_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_UAZ_3151_01_OCimport_02 : I_PKLGang_UAZ_3151_01_OCimport_01 { scope = 0; class EventHandlers; };

    class I_PKLGang_UAZ_3151_Open_01;
    class I_PKLGang_UAZ_3151_Open_01_OCimport_01 : I_PKLGang_UAZ_3151_Open_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_UAZ_3151_Open_01_OCimport_02 : I_PKLGang_UAZ_3151_Open_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
        };
    };

    class I_PKLGang_UAZ_3151_DShKM_01;
    class I_PKLGang_UAZ_3151_DShKM_01_OCimport_01 : I_PKLGang_UAZ_3151_DShKM_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_UAZ_3151_DShKM_01_OCimport_02 : I_PKLGang_UAZ_3151_DShKM_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class I_PKLGang_UAZ_3151_SPG_01;
    class I_PKLGang_UAZ_3151_SPG_01_OCimport_01 : I_PKLGang_UAZ_3151_SPG_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_UAZ_3151_SPG_01_OCimport_02 : I_PKLGang_UAZ_3151_SPG_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
            class CargoTurret_01;
        };
    };

    class I_PKLGang_ZiL_131_Open_01;
    class I_PKLGang_ZiL_131_Open_01_OCimport_01 : I_PKLGang_ZiL_131_Open_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_ZiL_131_Open_01_OCimport_02 : I_PKLGang_ZiL_131_Open_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class I_PKLGang_ZiL_131_Open_Flatbed_01;
    class I_PKLGang_ZiL_131_Open_Flatbed_01_OCimport_01 : I_PKLGang_ZiL_131_Open_Flatbed_01 { scope = 0; class EventHandlers; };
    class I_PKLGang_ZiL_131_Open_Flatbed_01_OCimport_02 : I_PKLGang_ZiL_131_Open_Flatbed_01_OCimport_01 { scope = 0; class EventHandlers; };

    class I_PKLGang_DShKm_Miniturret_01;
    class I_PKLGang_DShKm_Miniturret_01_OCimport_01 : I_PKLGang_DShKm_Miniturret_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_DShKm_Miniturret_01_OCimport_02 : I_PKLGang_DShKm_Miniturret_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_PKLGang_DShKM_01;
    class I_PKLGang_DShKM_01_OCimport_01 : I_PKLGang_DShKM_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_DShKM_01_OCimport_02 : I_PKLGang_DShKM_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class MainTurret;
        };
    };

    class I_PKLGang_Mi_8Unarmed_01;
    class I_PKLGang_Mi_8Unarmed_01_OCimport_01 : I_PKLGang_Mi_8Unarmed_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_Mi_8Unarmed_01_OCimport_02 : I_PKLGang_Mi_8Unarmed_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
        };
    };

    class I_PKLGang_MH_9Benches_01;
    class I_PKLGang_MH_9Benches_01_OCimport_01 : I_PKLGang_MH_9Benches_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_MH_9Benches_01_OCimport_02 : I_PKLGang_MH_9Benches_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
        };
    };

    class I_PKLGang_MH_9Unarmed_01;
    class I_PKLGang_MH_9Unarmed_01_OCimport_01 : I_PKLGang_MH_9Unarmed_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_MH_9Unarmed_01_OCimport_02 : I_PKLGang_MH_9Unarmed_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CopilotTurret;
        };
    };

    class I_PKLGang_Rhib_01;
    class I_PKLGang_Rhib_01_OCimport_01 : I_PKLGang_Rhib_01 { scope = 0; class EventHandlers; class Turrets; };
    class I_PKLGang_Rhib_01_OCimport_02 : I_PKLGang_Rhib_01_OCimport_01 { 
        class EventHandlers; 
        class Turrets : Turrets {
            class CargoTurret_01;
            class CargoTurret_02;
            class CargoTurret_03;
            class CargoTurret_04;
            class CargoTurret_05;
            class CargoTurret_06;
            class CargoTurret_07;
        };
    };


    class O_PKLGang_T41_Mescalero_01 : I_PKLGang_T41_Mescalero_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "T-41 Mescalero";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Pilot_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLGang_Pilot_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_Cessna\data\aircraft_e_wdl_co.paa'];_unit setObjectTextureGlobal [1,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_Cessna\data\decals\blank_ca.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "WDL";

    };

    class O_PKLGang_Rifleman_Unarmed_01 : I_PKLGang_Rifleman_Unarmed_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rifleman (Unarmed)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEI_B_U_Pants_02";

        linkedItems[] = {"UK3CB_V_SOV_CHICOM_GRN","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_V_SOV_CHICOM_GRN","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {};
        respawnWeapons[] = {};

        magazines[] = {};
        respawnMagazines[] = {};

        ALiVE_orbatCreator_loadout[] = {{},{},{},{"UK3CB_MEI_B_U_Pants_02",{{"FirstAidKit",1}}},{"UK3CB_V_SOV_CHICOM_GRN",{}},{},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Helicopter_Pilot_01 : I_PKLGang_Helicopter_Pilot_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Helicopter Pilot";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEI_B_U_Pants_02";

        linkedItems[] = {"UK3CB_V_SOV_CHICOM_GRN","rhs_gssh18","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_V_SOV_CHICOM_GRN","rhs_gssh18","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u"};
        respawnWeapons[] = {"rhs_weap_aks74u"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"UK3CB_MEI_B_U_Pants_02",{{"FirstAidKit",1},{"ToolKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"UK3CB_V_SOV_CHICOM_GRN",{{"rhs_30Rnd_545x39_7N6_AK",8,30},{"rhs_30Rnd_545x39_7N6M_AK",4,30}}},{},"rhs_gssh18","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Pilot_01 : I_PKLGang_Pilot_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Pilot";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEI_B_U_Pants_02";

        linkedItems[] = {"UK3CB_V_SOV_CHICOM_GRN","rhs_gssh18","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_V_SOV_CHICOM_GRN","rhs_gssh18","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u"};
        respawnWeapons[] = {"rhs_weap_aks74u"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"UK3CB_MEI_B_U_Pants_02",{{"FirstAidKit",1},{"ToolKit",1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{"UK3CB_V_SOV_CHICOM_GRN",{{"rhs_30Rnd_545x39_7N6_AK",8,30},{"rhs_30Rnd_545x39_7N6M_AK",7,30}}},{},"rhs_gssh18","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Snatcher_Medikit_01 : I_PKLGang_Snatcher_Medikit_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Snatcher (Medikit)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEC_C_Jeans_Tshirt_U_12";

        linkedItems[] = {"UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u"};
        respawnWeapons[] = {"rhs_weap_aks74u"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "UK3CB_CHD_B_B_Sidor_RIF_FLORA";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"UK3CB_MEC_C_Jeans_Tshirt_U_12",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",1,30}}},{},{"UK3CB_CHD_B_B_Sidor_RIF_FLORA",{{"Medikit",1},{"FirstAidKit",2},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Thug_Mines_01 : I_PKLGang_Thug_Mines_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Thug (Mines)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEC_C_Pants_U_02";

        linkedItems[] = {"UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u"};
        respawnWeapons[] = {"rhs_weap_aks74u"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "rhs_tortila_olive";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"UK3CB_MEC_C_Pants_U_02",{{"FirstAidKit",1},{"MiniGrenade",2,1},{"rhs_30Rnd_545x39_7N6M_AK",3,30}}},{},{"rhs_tortila_olive",{{"ToolKit",1},{"APERSTripMine_Wire_Mag",2,1},{"APERSMine_Range_Mag",2,1}}},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Dealer_Rifle_01 : I_PKLGang_Dealer_Rifle_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Dealer (Rifle)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEC_C_Pants_U_11";

        linkedItems[] = {"UK3CB_V_CW_Chestrig_2_Small","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_V_CW_Chestrig_2_Small","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u"};
        respawnWeapons[] = {"rhs_weap_aks74u"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"UK3CB_MEC_C_Pants_U_11",{{"FirstAidKit",1},{"MiniGrenade",1,1},{"rhs_30Rnd_545x39_7N6M_AK",1,30}}},{"UK3CB_V_CW_Chestrig_2_Small",{{"MiniGrenade",1,1},{"rhs_30Rnd_545x39_7N6M_AK",6,30}}},{},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Smuggler_UGL_01 : I_PKLGang_Smuggler_UGL_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Smuggler (UGL)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_ADC_C_Pants_U_25";

        linkedItems[] = {"UK3CB_V_CW_Chestrig_2_Small","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_V_CW_Chestrig_2_Small","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74_gp25"};
        respawnWeapons[] = {"rhs_weap_ak74_gp25"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25","rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25","rhs_30Rnd_545x39_7N6M_AK","rhs_VOG25"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74_gp25","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{"rhs_VOG25",1},""},{},{},{"UK3CB_ADC_C_Pants_U_25",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",2,30}}},{"UK3CB_V_CW_Chestrig_2_Small",{{"rhs_VOG25",3,1},{"rhs_30Rnd_545x39_7N6M_AK",8,30}}},{},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Scout_Rifle_01 : I_PKLGang_Scout_Rifle_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Scout (Rifle)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEC_C_Pants_U_13";

        linkedItems[] = {"UK3CB_V_CW_Chestrig_2_Small","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_V_CW_Chestrig_2_Small","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74"};
        respawnWeapons[] = {"rhs_weap_ak74"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"UK3CB_MEC_C_Pants_U_13",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",2,30}}},{"UK3CB_V_CW_Chestrig_2_Small",{{"MiniGrenade",2,1},{"rhs_30Rnd_545x39_7N6M_AK",8,30}}},{},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Watcher_Rifle_01 : I_PKLGang_Watcher_Rifle_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Watcher (Rifle)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEC_C_Pants_U_08";

        linkedItems[] = {"UK3CB_V_CW_Chestrig_2_Small","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_V_CW_Chestrig_2_Small","UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_ak74"};
        respawnWeapons[] = {"rhs_weap_ak74"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_30Rnd_545x39_7N6M_AK"};

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_ak74","rhs_acc_dtk1983","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{},{},{"UK3CB_MEC_C_Pants_U_08",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",2,30}}},{"UK3CB_V_CW_Chestrig_2_Small",{{"MiniGrenade",2,1},{"rhs_30Rnd_545x39_7N6M_AK",8,30}}},{},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Guard_Machine_Gun_01 : I_PKLGang_Guard_Machine_Gun_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Guard (Machine Gun)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEC_C_Pants_U_04";

        linkedItems[] = {"UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"UK3CB_RPK_74","hgun_Pistol_01_F"};
        respawnWeapons[] = {"UK3CB_RPK_74","hgun_Pistol_01_F"};

        magazines[] = {"UK3CB_RPK74_60rnd_545x39","10Rnd_9x21_Mag","UK3CB_RPK74_60rnd_545x39","10Rnd_9x21_Mag"};
        respawnMagazines[] = {"UK3CB_RPK74_60rnd_545x39","10Rnd_9x21_Mag","UK3CB_RPK74_60rnd_545x39","10Rnd_9x21_Mag"};

        backpack = "rhs_tortila_grey";

        ALiVE_orbatCreator_loadout[] = {{"UK3CB_RPK_74","","","",{"UK3CB_RPK74_60rnd_545x39",60},{},""},{},{"hgun_Pistol_01_F","","","",{"10Rnd_9x21_Mag",10},{},""},{"UK3CB_MEC_C_Pants_U_04",{{"FirstAidKit",1},{"10Rnd_9x21_Mag",2,10}}},{},{"rhs_tortila_grey",{{"UK3CB_RPK74_60rnd_545x39",9,60}}},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Hireling_Launcher_01 : I_PKLGang_Hireling_Launcher_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Hireling (Launcher)";
        side = 2;
        faction = "O_PKLGang";

        identityTypes[] = {"Head_Asian","LanguageFRE_F"};

        uniformClass = "UK3CB_MEC_C_Pants_U_18";

        linkedItems[] = {"UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};
        respawnlinkedItems[] = {"UK3CB_H_Bandanna_Brown_Check","ItemMap","ItemRadio","ItemCompass","ItemWatch"};

        weapons[] = {"rhs_weap_aks74u","rhs_weap_rpg7"};
        respawnWeapons[] = {"rhs_weap_aks74u","rhs_weap_rpg7"};

        magazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_rpg7_PG7VL_mag","rhs_30Rnd_545x39_7N6M_AK"};
        respawnMagazines[] = {"rhs_30Rnd_545x39_7N6M_AK","rhs_rpg7_PG7VL_mag","rhs_30Rnd_545x39_7N6M_AK"};

        backpack = "rhs_tortila_grey";

        ALiVE_orbatCreator_loadout[] = {{"rhs_weap_aks74u","rhs_acc_pgs64_74u","","",{"rhs_30Rnd_545x39_7N6M_AK",30},{},""},{"rhs_weap_rpg7","","","",{"rhs_rpg7_PG7VL_mag",1},{},""},{},{"UK3CB_MEC_C_Pants_U_18",{{"FirstAidKit",1},{"rhs_30Rnd_545x39_7N6M_AK",2,30}}},{},{"rhs_tortila_grey",{{"rhs_30Rnd_545x39_7N6M_AK",3,30},{"rhs_rpg7_PG7VL_mag",3,1}}},"UK3CB_H_Bandanna_Brown_Check","",{},{"ItemMap","","ItemRadio","ItemCompass","ItemWatch",""}};


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {_this = _this select 0;sleep 0.2; _backpack = gettext(configfile >> 'cfgvehicles' >> (typeof _this) >> 'backpack'); waituntil {sleep 0.2; backpack _this == _backpack};if !(_this getVariable ['ALiVE_OverrideLoadout',false]) then {_loadout = getArray(configFile >> 'CfgVehicles' >> (typeOf _this) >> 'ALiVE_orbatCreator_loadout'); _this setunitloadout _loadout;reload _this};};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_UAZ_3151_01 : I_PKLGang_UAZ_3151_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ-3151";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Dealer_Rifle_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_ind_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_PKLGang_UAZ_3151_Open_01 : I_PKLGang_UAZ_3151_Open_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ 3151 (Open)";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Watcher_Rifle_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_ind_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_PKLGang_UAZ_3151_DShKM_01 : I_PKLGang_UAZ_3151_DShKM_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ 3151 (DShKM)";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Watcher_Rifle_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLGang_Dealer_Rifle_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_ind_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_mount_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_PKLGang_UAZ_3151_SPG_01 : I_PKLGang_UAZ_3151_SPG_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "UAZ 3151 (SPG-9)";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Watcher_Rifle_01";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLGang_Scout_Rifle_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_main_ind_co.paa'];_unit setObjectTextureGlobal [1,'rhsafrf\addons\rhs_a2port_car\uaz\data\uaz_mount_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_PKLGang_ZiL_131_Open_01 : I_PKLGang_ZiL_131_Open_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "ZiL-131 (Open)";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Scout_Rifle_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_cargo_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_cabin_co.paa'];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_interior_co.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_wheels_co.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_base_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_PKLGang_ZiL_131_Open_Flatbed_01 : I_PKLGang_ZiL_131_Open_Flatbed_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "ZiL-131 (Open/Flatbed)";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Dealer_Rifle_01";


        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_cargo_co.paa'];_unit setObjectTextureGlobal [1,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_cabin_co.paa'];_unit setObjectTextureGlobal [2,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_interior_co.paa'];_unit setObjectTextureGlobal [3,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_wheels_co.paa'];_unit setObjectTextureGlobal [4,'\rhsafrf\addons\rhs_zil131\data\rhs_zil131_base_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "standard";

    };

    class O_PKLGang_DShKm_Miniturret_01 : I_PKLGang_DShKm_Miniturret_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "DShKm Miniturret";
        side = 2;
        faction = "O_PKLGang";
        crew = "rhsgref_ins_g_rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLGang_Watcher_Rifle_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_DShKM_01 : I_PKLGang_DShKM_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "DShKM";
        side = 2;
        faction = "O_PKLGang";
        crew = "rhsgref_ins_g_rifleman";

        class Turrets : Turrets {
            class MainTurret : MainTurret { gunnerType = "O_PKLGang_Dealer_Rifle_01"; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;

    };

    class O_PKLGang_Mi_8Unarmed_01 : I_PKLGang_Mi_8Unarmed_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Mi-8 (Unarmed)";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Helicopter_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = "O_PKLGang_Helicopter_Pilot_01"; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_MI8\data\khk_mi8_body_co.paa'];_unit setObjectTextureGlobal [1,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_MI8\data\khk_mi8_det_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "KHK";

    };

    class O_PKLGang_MH_9Benches_01 : I_PKLGang_MH_9Benches_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "MH-9 (Benches)";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Helicopter_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_MH9\data\ion_heli_light_01_ext_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "BLK";

    };

    class O_PKLGang_MH_9Unarmed_01 : I_PKLGang_MH_9Unarmed_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "MH-9 (Unarmed)";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Helicopter_Pilot_01";

        class Turrets : Turrets {
            class CopilotTurret : CopilotTurret { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'UK3CB_Factions\addons\UK3CB_Factions_Vehicles\air\UK3CB_Factions_Vehicles_MH9\data\ion_heli_light_01_ext_co.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "BLK";

    };

    class O_PKLGang_Rhib_01 : I_PKLGang_Rhib_01_OCimport_02 {
        author = "Recon Chicken";
        scope = 2;
        scopeCurator = 2;
        displayName = "Rhib";
        side = 2;
        faction = "O_PKLGang";
        crew = "I_PKLGang_Dealer_Rifle_01";

        class Turrets : Turrets {
            class CargoTurret_01 : CargoTurret_01 { gunnerType = ""; };
            class CargoTurret_02 : CargoTurret_02 { gunnerType = ""; };
            class CargoTurret_03 : CargoTurret_03 { gunnerType = ""; };
            class CargoTurret_04 : CargoTurret_04 { gunnerType = ""; };
            class CargoTurret_05 : CargoTurret_05 { gunnerType = ""; };
            class CargoTurret_06 : CargoTurret_06 { gunnerType = ""; };
            class CargoTurret_07 : CargoTurret_07 { gunnerType = ""; };
        };



        class EventHandlers : EventHandlers {
            class CBA_Extended_EventHandlers : CBA_Extended_EventHandlers_base {};

            class ALiVE_orbatCreator {
                init = "if (local (_this select 0)) then {_onSpawn = {sleep 0.3; _unit = _this select 0;_unit setObjectTextureGlobal [0,'\A3\Boat_F_Exp\Boat_Transport_02\Data\Boat_Transport_02_exterior_civilian_CO.paa'];_unit setObjectTextureGlobal [1,'\A3\Boat_F_Exp\Boat_Transport_02\Data\Boat_Transport_02_interior_2_civilian_CO.paa'];};_this spawn _onSpawn;(_this select 0) addMPEventHandler ['MPRespawn', _onSpawn];};";
            };

        };

        // custom attributes (do not delete)
        ALiVE_orbatCreator_owned = 1;
        ALiVE_orbatCreator_texture = "Civilian";

    };

};